spring:
  application:
    name: micro-business-impl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.98.73:3306/ngmc5?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ngV5123

mybatis:
    mapper-locations: classpath:mybatis/mapper/*.xml
    type-aliases-package: com.business.microbusiness.entity


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true
    #    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 5
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 2
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
