version: '3'
services:
   db:
     image: centos/mysql-57-centos7
     container_name: mysql57
     volumes:
       #- db_data:/var/lib/mysql/data
       - ./mysql/conf:/etc/mysql/conf.d
       - ./dbdata:/var/lib/mysql
      # - ./mysql/init:/docker-entrypoint-initdb.d/
     environment:
       MYSQL_ROOT_PASSWORD: 123456
     ports:
      - '3307:3306'
   redis:
     restart: always
     ports:
      - '6379'
     image: redis
     #container_name: redis1
     volumes: 
       - ./redis/data:/data
     command: redis-server --appendonly "yes" --requirepass "123456" --notify-keyspace-events Eglx
   rabbitmq: 
     restart: always
     image: rabbitmq
     ports: 
       - "4369:4369"
       - "5671:5671"
       - "5672:5672"
       - "15671:15671"
       - "15672:15672"

     container_name: rabbitmq
     volumes:
       - ./rabbitmq/data:/var/rabbitmq/lib
     environment: 
       RABBITMQ_DEFAULT_USER: admin
       RABBITMQ_DEFAULT_PASS: 123456
     #command: rabbitmq-plugins enable rabbitmq_management
   zk1: 
     image: zookeeper
     restart: always
     container_name: zk1
     ports:
       - '2181:2181'
     environment:
       ZOO_MY_ID: 1
       ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
   zk2:
     image: zookeeper
     restart: always
     container_name: zk2
     ports:
       - '2182:2181'
     environment:
       ZOO_MY_ID: 2
       ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
   zk3:
     image: zookeeper
     restart: always
     container_name: zk3
     ports:
       - '2183:2181'
     environment:
       ZOO_MY_ID: 3
       ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
   etcd0:
     image: quay.io/coreos/etcd
     ports:
       - "2379:2379"
     volumes:
       - ./etcd/data0:/etcd_data
     command:
       - /usr/local/bin/etcd
       - -name
       - etcd0
       - --data-dir
       - /etcd_data
       - -advertise-client-urls
       - http://etcd0:2379
       - -listen-client-urls
       - http://0.0.0.0:2379
       - -initial-advertise-peer-urls
       - http://etcd0:2380
       - -listen-peer-urls
       - http://0.0.0.0:2380
       - -initial-cluster
       - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
   etcd1:
     image: quay.io/coreos/etcd
     ports:
       - "2380:2379"
     volumes:
       - ./etcd/data1:/etcd_data
     command:
       - /usr/local/bin/etcd
       - -name
       - etcd1
       - --data-dir
       - /etcd_data
       - -advertise-client-urls
       - http://etcd1:2379
       - -listen-client-urls
       - http://0.0.0.0:2379
       - -initial-advertise-peer-urls
       - http://etcd1:2380
       - -listen-peer-urls
       - http://0.0.0.0:2380
       - -initial-cluster
       - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
   etcd2:
     image: quay.io/coreos/etcd
     ports:
       - "2381:2379"
     volumes:
       - ./etcd/data2:/etcd_data
     command:
       - /usr/local/bin/etcd
       - -name
       - etcd2
       - --data-dir
       - /etcd_data
       - -advertise-client-urls
       - http://etcd2:2379
       - -listen-client-urls
       - http://0.0.0.0:2379
       - -initial-advertise-peer-urls
       - http://etcd2:2380
       - -listen-peer-urls
       - http://0.0.0.0:2380
       - -initial-cluster
       - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
