server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10

spring:
  application:
    name: micro-business-consume-hystrix
ribbon:
  eager-load:
    enabled: true
    clients:
        micro-business-impl
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info和health
  endpoint:
    health:
      show-details: always #默认是never
  server:
    port: 8185
info:
    app:
      version: 1.1
      name: aut   #/actuator/info 自定义的info端点 否则是空的