server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    #eureka client刷新本地缓存时间
    #默认30s
    registry-fetch-interval-seconds: 3
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
spring:
  application:
    name: micro-gateway-zuul

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info和health
  endpoint:
    health:
      show-details: always #默认是never
info:
    app:
      version: 1.1
      name: aut   #/actuator/info 自定义的info端点 否则是空的
zuul:
  ribbon:
    eager-load:
        enabled: true
        clients:
          micro-business-consume-hystrix